version: "3.9"

services:
    web:
        image: nginx:latest 
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./certs:/etc/nginx/certs
            - ./volumes/application:/var/www/
            - ./build/config/default.conf:/etc/nginx/conf.d/default.conf
            - ./build/config/fpm73.conf:/etc/nginx/fpm73.conf
            - ./build/config/fpm74.conf:/etc/nginx/fpm74.conf
            - ./build/config/fpm81.conf:/etc/nginx/fpm81.conf
            - ./build/config/fpm82.conf:/etc/nginx/fpm82.conf
        links:
            - php-fpm73
            - php-fpm74
            - php-fpm81
            - mysql:mysql
    php-fpm73:
        build:
          context: build/php73
        user: "1000:1000"
        volumes:
            - ./volumes/application:/var/www/
        ports:
            - "9000:9000"
    php-fpm74:
        build:
          context: build/php74
        user: "1000:1000"
        volumes:
            - ./volumes/application:/var/www/
        ports:
            - "9001:9000"
    php-fpm81:
        build:
          context: build/php81
        user: "1000:1000"
        volumes:
            - ./volumes/application:/var/www/
        ports:
            - "9003:9000"
    mysql:
      build:
        context: build/mysql
        args:
          LOCAL_USER_ID: 1000
          LOCAL_GROUP_ID: 1000
      volumes:
        - ./volumes/mysql:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=opwer384
        - TZ=Europe/Berlin
      ports:
        - "3306:3306"
